### PR TITLE
Use unminified css and remove minified

### LINKED ISSUE #60: We're serving the minified css but it's not in the build
Currently (as of 075ba86), the CSS referenced by the html is `css_new/uswds.min.css`. Normally, that would be built from the source file `css_new/uswds.css`. But it's not actually being minified in the build process. The minified file we're actually serving is committed to the repo, so it's static unless anyone manually updates it.

Heads up: this bug was very hard to find because the mapping between the source file and minified file (`css_new/uswds.min.css.map`) is also a static file committed to the repo. So looking in the browser's dev tools shows unminified css that won't match the actual unminified css you're editing.

### PR DESCRIPTION
**Pull request by NickSto**
Fixes #60

### CODE REVIEW

**Comment by sheldon-b** [comment]
Almost! This looks good in desktop mode but I do notice that in mobile mode the responsiveness is broken. Let's fix that before merging this
Screenshot 2024-02-25 at 9 09 29 PM

**Comment by sheldon-b** [comment]
(note on how I tested it: the CI step for `deploy/netlify` links to a preview environment where this PR gets deployed to)

**Comment by NickSto** [comment]
I don't see the mobile issue anymore, nor the different font size I noticed previously 🤔

I've checked in the local version and the Netlify preview in Firefox and Chrome.

If someone else can verify, I think this is ready to merge.

**Comment by sheldon-b** [comment]
@NickSto I still see the logo being broken in the netlify preview deployment. I did merge your other PR though

**Comment by sheldon-b** [comment]
Got it. Do we need to migrate your fix from the logo-fixing PR into this PR before merging then, to make sure we don't break the logo again?

**Pull request closed without merging**
